# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys


def generate_html_figures(app):

    ### Create folder to store temp data
    path_data_stats = os.path.join(os.getcwd(), "data_stats")
    if not os.path.isdir(path_data_stats):
        os.makedirs(path_data_stats)

    ### Get exclude.yml from latest release of multi-subject
    path_zip_data_multisubject = os.path.join(path_data_stats, "data_multisubject.zip")
    os.system(
        """
    LOCATION=$(curl -s https://api.github.com/repos/spine-generic/data-multi-subject/releases/latest \
    | grep "tag_name" \
    | awk '{print "https://github.com/spine-generic/data-multi-subject/archive/" substr($2, 2, length($2)-3) ".zip"}') \
    ;curl -L -o """
        + path_zip_data_multisubject
        + """ $LOCATION"""
    )
    ### Extract only *exclude.yml
    os.system(
        "unzip -j " + path_zip_data_multisubject + " *exclude.yml -d" + path_data_stats
    )

    ### Get results from latest release of multi-subject
    # TODO: This is currently hard-coded to r20201130, rather than the latest release,
    # to address https://github.com/spine-generic/spine-generic/issues/268
    path_zip_results_multisubject = os.path.join(path_data_stats, "results.zip")
    # os.system(
    #     """
    # LOCATION=$(curl -s https://api.github.com/repos/spine-generic/data-multi-subject/releases/latest \
    # | grep "tag_name" \
    # | awk '{print "https://github.com/spine-generic/data-multi-subject/releases/download/" substr($2, 2, length($2)-3) "/results.zip"}') \
    # ;curl -L -o """
    #     + path_zip_results_multisubject
    #     + """ $LOCATION"""
    # )
    os.system(f'curl -L -o {path_zip_results_multisubject} https://github.com/spine-generic/data-multi-subject/releases/download/r20201130/results.zip')

    ### Extract only *.csv
    os.system(
        "unzip -j " + path_zip_results_multisubject + " *.csv -d" + path_data_stats
    )
    os.system(
        "unzip -j " + path_zip_results_multisubject + " *.tsv -d" + path_data_stats
    )

    ###Generate html figures
    from spinegeneric.cli import generate_figure

    generate_figure.main(
        [
            "-path-results",
            path_data_stats,
            "-exclude",
            str(path_data_stats) + "/exclude.yml",
            "-output-html",
        ]
    )
    os.system("mv *.html ../_static")


def setup(app):
    app.connect("builder-inited", generate_html_figures)


sys.path.insert(0, os.path.abspath("../"))
print(sys.path)
from spinegeneric import __version__


# -- Project information -----------------------------------------------------

project = "spine-generic"
copyright = "2019, Julien Cohen-Adad"
author = "Julien Cohen-Adad"

# The short X.Y version
version = __version__

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {
#    'collapse_navigation': False,
#    'display_version': False,
#    'navigation_depth': 4,
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "spine-genericdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "spine-generic.tex",
        "spine-generic Documentation",
        "Julien Cohen-Adad",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "spine-generic", "spine-generic Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "spine-generic",
        "spine-generic Documentation",
        author,
        "spine-generic",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]
